/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_NativeSleep */

#ifndef _Included_utils_NativeSleep
#define _Included_utils_NativeSleep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_NativeSleep
 * Method:    sleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_common_NativeSleep_sleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
